### ISSUE TITLE
Author line is being split in generated themes

### ISSUE THREAD

**Issue by joshbode** [tinted-theming/tinted-builder-rust#6]
Sorry if this isn't the right place to report this, but I think the `tinted-theming-bot` is developed here.

The `author` tag is being split by the builder leading to part of the line becoming uncommented. This may be due to the line being longer than some critical threshold, since it doesn't appear to affect all built themes.

See:
https://github.com/tinted-theming/tinted-shell/commit/0925c10da420acc5e3b68a2b0fc39ae76816d89a#diff-2ef117137d09adaa201c1850fad18550932f4b64fa1b324f115c275cc9a55443R4-R5

I believe this is the source of the spec file for the theme:
https://github.com/Misterio77/base16-spaceduck-scheme/blob/main/spaceduck.yaml#L2

**Comment by JamyGolden** [comment]
Thanks for catching, this. Interesting, it seems to be a bug with base16-builder-go too. I'll fix this weekend.

**Comment by JamyGolden** [comment]
The easiest way to fix this right now is to remove the multilines from the schemes themselves.I've created a PR fix https://github.com/tinted-theming/schemes/pull/28

**Comment by JamyGolden** [comment]
Just merged, not only is it the easiest way to fix, I think it's actually the only way to fix it since the mustache template is being rendered correctly, so the restriction of 1 line for the meta info needs to move to the scheme files.

**Comment by joshbode** [comment]
Awesome - thanks @JamyGolden :)

**Comment by joshbode** [comment]
Does anything need to be triggered to propagate this to `tinted-theming/base16-shell` (and any other downstream targets)?
